pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/santoshbd67/pre-screening-assignment.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker-compose -f assignment/docker-compose.yml up --build -d'
            }
        }
    }
}
